2020-05-14 19:22:19,640 - TeleBot - ERROR -TypeError occurred, args=('list indices must be integers or slices, not str',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data['weather']['main'])
TypeError: list indices must be integers or slices, not str

2020-05-14 19:24:39,271 - TeleBot - ERROR -TypeError occurred, args=('string indices must be integers',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 50, in location
    print(dat['weather']['main'])
TypeError: string indices must be integers

2020-05-14 19:31:40,989 - TeleBot - ERROR -KeyError occurred, args=(0,)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data[0])
KeyError: 0

2020-05-14 19:33:14,435 - TeleBot - ERROR -KeyError occurred, args=(0,)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data[0]['weather']['main'])
KeyError: 0

2020-06-15 18:14:41,180 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:14:41,180 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
2020-06-15 18:14:45,085 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:14:45,085 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
2020-06-15 18:14:49,744 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:14:49,745 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
2020-06-15 18:14:55,906 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:14:55,906 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
2020-06-15 18:15:01,316 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:15:01,316 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
2020-06-15 18:15:08,988 - TeleBot - ERROR -ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

2020-06-15 18:15:08,989 - TeleBot - ERROR -A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
