2020-05-14 19:22:19,640 - TeleBot - ERROR -TypeError occurred, args=('list indices must be integers or slices, not str',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data['weather']['main'])
TypeError: list indices must be integers or slices, not str

2020-05-14 19:24:39,271 - TeleBot - ERROR -TypeError occurred, args=('string indices must be integers',)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 50, in location
    print(dat['weather']['main'])
TypeError: string indices must be integers

2020-05-14 19:31:40,989 - TeleBot - ERROR -KeyError occurred, args=(0,)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data[0])
KeyError: 0

2020-05-14 19:33:14,435 - TeleBot - ERROR -KeyError occurred, args=(0,)
Traceback (most recent call last):
  File "/home/danny/Dropbox/Programming/pythons/Env/env/lib64/python3.7/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 49, in location
    print(data[0]['weather']['main'])
KeyError: 0

